//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingAndAnalysis1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleProduct = new HashSet<SaleProduct>();
        }
    
        public int Id { get; set; }
        public int SaleTypeId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal TotalCost { get; set; }
        public int CashRegisterId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual CashRegister CashRegister { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SaleType SaleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProduct> SaleProduct { get; set; }
    }
}
